import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import React from "react";

export const metadata: Metadata = {
  title: "Sample Leaderbored Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <main className="page-wrapper">
          {children}
        </main>
      </body>
    </html>
  );
}
